from __future__ import annotations

from enum import Enum


class AgentState(str, Enum):
    START = "START"
    UNDERSTAND = "UNDERSTAND"
    INSPECT_WORKSPACE = "INSPECT_WORKSPACE"
    PLAN = "PLAN"
    SEARCH = "SEARCH"
    READ = "READ"
    FORM_CHANGE_PLAN = "FORM_CHANGE_PLAN"
    EDIT = "EDIT"
    DIFF_REVIEW = "DIFF_REVIEW"
    TEST = "TEST"
    ANALYZE_FAILURE = "ANALYZE_FAILURE"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMEOUT = "TIMEOUT"
